version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: "15.12.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build every packages
      - run:
          command: yarn test-all
          name: Run all tests
workflows:
  node-tests:
    jobs:
      - test
